# Generated by Django 6.0.3 on 2026-04-13 23:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('asistencia', '0001_initial'),
        ('ninos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='asistencia',
            name='id_nino',
            field=models.ForeignKey(db_column='id_nino', on_delete=django.db.models.deletion.CASCADE, related_name='asistencias', to='ninos.nino'),
        ),
        migrations.AlterUniqueTogether(
            name='asistencia',
            unique_together={('id_nino', 'fecha')},
        ),
    ]
