# Generated by Django 6.0.3 on 2026-04-13 23:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nino',
            fields=[
                ('id_nino', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('fecha_nacimiento', models.DateField()),
                ('edad', models.IntegerField(blank=True, null=True)),
                ('foto', models.TextField(blank=True, null=True)),
                ('info_medica', models.TextField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'nino',
            },
        ),
        migrations.CreateModel(
            name='PersonaAutorizada',
            fields=[
                ('id_persona', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('ci', models.CharField(max_length=20)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('codigo_seguridad', models.CharField(max_length=50)),
                ('activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id_nino', models.ForeignKey(db_column='id_nino', on_delete=django.db.models.deletion.CASCADE, related_name='personas_autorizadas', to='ninos.nino')),
            ],
            options={
                'db_table': 'persona_autorizada',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='RetiroNino',
            fields=[
                ('id_retiro', models.AutoField(primary_key=True, serialize=False)),
                ('codigo_seguridad_usado', models.CharField(max_length=50)),
                ('observacion', models.TextField(blank=True, null=True)),
                ('fecha_hora_retiro', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('id_nino', models.ForeignKey(db_column='id_nino', on_delete=django.db.models.deletion.CASCADE, related_name='retiros', to='ninos.nino')),
                ('id_persona_autorizada', models.ForeignKey(db_column='id_persona_autorizada', on_delete=django.db.models.deletion.CASCADE, related_name='retiros', to='ninos.personaautorizada')),
                ('registrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='retiros_registrados', to='usuarios.usuario')),
            ],
            options={
                'db_table': 'retiro_nino',
                'ordering': ['-fecha_hora_retiro'],
            },
        ),
        migrations.CreateModel(
            name='TutorNino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relacion', models.CharField(blank=True, max_length=50, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id_nino', models.ForeignKey(db_column='id_nino', on_delete=django.db.models.deletion.CASCADE, related_name='tutores', to='ninos.nino')),
            ],
            options={
                'db_table': 'tutor_nino',
            },
        ),
    ]
