# Generated by Django 6.0.3 on 2026-04-13 23:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ninos', '0001_initial'),
        ('tutores', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutornino',
            name='id_tutor',
            field=models.ForeignKey(db_column='id_tutor', on_delete=django.db.models.deletion.CASCADE, related_name='ninos', to='tutores.tutor'),
        ),
        migrations.AlterUniqueTogether(
            name='tutornino',
            unique_together={('id_tutor', 'id_nino')},
        ),
    ]
