# Generated by Django 6.0.3 on 2026-04-13 23:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ninos', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alimentacion',
            fields=[
                ('id_alimentacion', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_comida', models.CharField(max_length=100)),
                ('horario', models.TimeField()),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id_nino', models.ForeignKey(db_column='id_nino', on_delete=django.db.models.deletion.CASCADE, related_name='alimentaciones', to='ninos.nino')),
            ],
            options={
                'db_table': 'alimentacion',
            },
        ),
        migrations.CreateModel(
            name='Medicacion',
            fields=[
                ('id_medicacion', models.AutoField(primary_key=True, serialize=False)),
                ('medicamento', models.CharField(max_length=100)),
                ('dosis', models.CharField(max_length=50)),
                ('hora', models.TimeField()),
                ('activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id_nino', models.ForeignKey(db_column='id_nino', on_delete=django.db.models.deletion.CASCADE, related_name='medicaciones', to='ninos.nino')),
            ],
            options={
                'db_table': 'medicacion',
            },
        ),
        migrations.CreateModel(
            name='Salud',
            fields=[
                ('id_salud', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('sintomas', models.TextField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id_nino', models.ForeignKey(db_column='id_nino', on_delete=django.db.models.deletion.CASCADE, related_name='registros_salud', to='ninos.nino')),
            ],
            options={
                'db_table': 'salud',
                'ordering': ['-fecha'],
            },
        ),
    ]
