# Generated by Django 6.0.3 on 2026-05-12 15:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guarderias', '0001_initial'),
        ('salud', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alimentacion',
            name='id_guarderia',
            field=models.ForeignKey(db_column='id_guarderia', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alimentacion', to='guarderias.guarderia'),
        ),
        migrations.AddField(
            model_name='medicacion',
            name='id_guarderia',
            field=models.ForeignKey(db_column='id_guarderia', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='medicacion', to='guarderias.guarderia'),
        ),
        migrations.AddField(
            model_name='salud',
            name='id_guarderia',
            field=models.ForeignKey(db_column='id_guarderia', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='salud', to='guarderias.guarderia'),
        ),
    ]
