# Generated by Django 6.0.3 on 2026-03-29 21:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('salas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Camara',
            fields=[
                ('id_camara', models.AutoField(primary_key=True, serialize=False)),
                ('url_stream', models.TextField()),
                ('activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id_sala', models.ForeignKey(db_column='id_sala', on_delete=django.db.models.deletion.CASCADE, related_name='camaras', to='salas.sala')),
            ],
            options={
                'db_table': 'camara',
            },
        ),
    ]
