# Generated by Django 6.0.3 on 2026-04-13 23:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('camaras', '0001_initial'),
        ('salas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='camara',
            name='id_sala',
            field=models.ForeignKey(db_column='id_sala', on_delete=django.db.models.deletion.CASCADE, related_name='camaras', to='salas.sala'),
        ),
    ]
