# Generated by Django 6.0.3 on 2026-06-21 01:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comunicacion', '0001_initial'),
        ('guarderias', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensaje',
            name='id_guarderia',
            field=models.ForeignKey(db_column='id_guarderia', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mensajes', to='guarderias.guarderia'),
        ),
        migrations.AddField(
            model_name='notificacion',
            name='id_guarderia',
            field=models.ForeignKey(db_column='id_guarderia', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to='guarderias.guarderia'),
        ),
    ]
