# Generated by Django 6.0.3 on 2026-03-30 23:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('niños', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonaAutorizada',
            fields=[
                ('id_persona', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('ci', models.CharField(max_length=20)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('codigo_seguridad', models.CharField(max_length=50)),
                ('activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id_nino', models.ForeignKey(db_column='id_nino', on_delete=django.db.models.deletion.CASCADE, related_name='personas_autorizadas', to='niños.nino')),
            ],
            options={
                'db_table': 'persona_autorizada',
                'ordering': ['nombre'],
            },
        ),
    ]
