# Generated by Django 6.0.3 on 2026-03-29 21:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('niños', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id_servicio', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tipo', models.CharField(choices=[('mensual', 'Mensual'), ('eventual', 'Eventual'), ('alimentacion', 'Alimentación'), ('transporte', 'Transporte'), ('otro', 'Otro')], default='mensual', max_length=50)),
                ('activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'servicio',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id_pago', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('pagado', 'Pagado'), ('anulado', 'Anulado')], default='pendiente', max_length=50)),
                ('activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id_nino', models.ForeignKey(db_column='id_nino', on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='niños.nino')),
            ],
            options={
                'db_table': 'pago',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='DetallePago',
            fields=[
                ('id_detalle', models.AutoField(primary_key=True, serialize=False)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id_pago', models.ForeignKey(db_column='id_pago', on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='servicios.pago')),
                ('id_servicio', models.ForeignKey(db_column='id_servicio', on_delete=django.db.models.deletion.CASCADE, related_name='detalles_pago', to='servicios.servicio')),
            ],
            options={
                'db_table': 'detalle_pago',
            },
        ),
        migrations.CreateModel(
            name='NinoServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id_nino', models.ForeignKey(db_column='id_nino', on_delete=django.db.models.deletion.CASCADE, related_name='servicios', to='niños.nino')),
                ('id_servicio', models.ForeignKey(db_column='id_servicio', on_delete=django.db.models.deletion.CASCADE, related_name='ninos', to='servicios.servicio')),
            ],
            options={
                'db_table': 'nino_servicio',
                'unique_together': {('id_nino', 'id_servicio')},
            },
        ),
    ]
