# Generated by Django 6.0.3 on 2026-04-13 23:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ninos', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Personal',
            fields=[
                ('id_personal', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('tipo', models.CharField(choices=[('maestra', 'Maestra'), ('auxiliar', 'Auxiliar'), ('enfermera', 'Enfermera'), ('cocinera', 'Cocinera'), ('seguridad', 'Seguridad'), ('otro', 'Otro')], default='maestra', max_length=50)),
                ('activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'personal',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Sala',
            fields=[
                ('id_sala', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('edad_min', models.IntegerField()),
                ('edad_max', models.IntegerField()),
                ('cupo_max', models.IntegerField()),
                ('activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'sala',
                'ordering': ['edad_min'],
            },
        ),
        migrations.CreateModel(
            name='AsignacionNinoSala',
            fields=[
                ('id_asignacion', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id_nino', models.ForeignKey(db_column='id_nino', on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones_sala', to='ninos.nino')),
                ('id_sala', models.ForeignKey(db_column='id_sala', on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones', to='salas.sala')),
            ],
            options={
                'db_table': 'asignacion_nino_sala',
            },
        ),
        migrations.CreateModel(
            name='PersonalSala',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id_personal', models.ForeignKey(db_column='id_personal', on_delete=django.db.models.deletion.CASCADE, related_name='salas', to='salas.personal')),
                ('id_sala', models.ForeignKey(db_column='id_sala', on_delete=django.db.models.deletion.CASCADE, related_name='personal', to='salas.sala')),
            ],
            options={
                'db_table': 'personal_sala',
                'unique_together': {('id_personal', 'id_sala')},
            },
        ),
    ]
