# Generated by Django 6.0.3 on 2026-04-13 23:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ninos', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actividad',
            fields=[
                ('id_actividad', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('pedagogica', 'Pedagógica'), ('recreativa', 'Recreativa'), ('deportiva', 'Deportiva'), ('artistica', 'Artística'), ('social', 'Social'), ('otro', 'Otro')], max_length=50)),
                ('descripcion', models.TextField()),
                ('fecha', models.DateField()),
                ('activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id_nino', models.ForeignKey(db_column='id_nino', on_delete=django.db.models.deletion.CASCADE, related_name='actividades', to='ninos.nino')),
            ],
            options={
                'db_table': 'actividad',
                'ordering': ['-fecha'],
            },
        ),
    ]
