# Generated by Django 6.0.3 on 2026-04-13 23:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bitacora',
            fields=[
                ('id_bitacora', models.AutoField(primary_key=True, serialize=False)),
                ('accion', models.CharField(choices=[('INSERT', 'Inserción'), ('UPDATE', 'Actualización'), ('DELETE', 'Eliminación')], max_length=50)),
                ('tabla', models.CharField(max_length=50)),
                ('id_registro', models.IntegerField(blank=True, null=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('id_usuario', models.ForeignKey(db_column='id_usuario', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bitacoras', to='usuarios.usuario')),
            ],
            options={
                'db_table': 'bitacora',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='HistorialCambios',
            fields=[
                ('id_historial', models.AutoField(primary_key=True, serialize=False)),
                ('tabla', models.CharField(max_length=50)),
                ('id_registro', models.IntegerField()),
                ('campo', models.CharField(max_length=50)),
                ('valor_anterior', models.TextField(blank=True, null=True)),
                ('valor_nuevo', models.TextField(blank=True, null=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('id_usuario', models.ForeignKey(db_column='id_usuario', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historial_cambios', to='usuarios.usuario')),
            ],
            options={
                'db_table': 'historial_cambios',
                'ordering': ['-fecha'],
            },
        ),
    ]
