# Generated by Django 6.0.3 on 2026-05-14 01:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditoria', '0001_initial'),
        ('guarderias', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bitacora',
            name='id_guarderia',
            field=models.ForeignKey(db_column='id_guarderia', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bitacoras', to='guarderias.guarderia'),
        ),
        migrations.AddField(
            model_name='historialcambios',
            name='id_guarderia',
            field=models.ForeignKey(db_column='id_guarderia', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='historial_cambios', to='guarderias.guarderia'),
        ),
    ]
